HerbalProject/Controllers/HerbController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using herbDllProj;

namespace HerbalProject.Controllers
{
    public class HerbController : Controller
    {
        private static HerbalList _herbalList;

        public HerbController()
        {
            if (_herbalList == null)
            {
                _herbalList = new HerbalList();
            }

        }

        [HttpGet]
        public ActionResult Index(string name)
        {
            if (name == null)
            {
                return View("_nothingToShow");
            }
            herbDllProj.herbals temp = _herbalList.herbals.Find(n => n.name_latin == name.Replace('_', ' ').Replace('!', '.'));
            if (temp == null)
            {
                return View("_nothingToShow");
            }
            ViewBag.relatedHerbs = _herbalList.getRelatedHerbs(temp.name_latin);

            StringBuilder sb = new StringBuilder();

            foreach (string item in temp.russianNames)
            {
                sb.Append(item + ",");
            }
            ViewBag.Description = sb.ToString().TrimEnd(',');
            return View(temp);
        }

    }
}

HerbalProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using herbDllProj;

namespace HerbalProject.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {

            return View();

        }
        public ActionResult PageNotFound()
        {
            return View();
        }
    }
}

HerbalProject/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using herbDllProj;

namespace HerbalProject.Controllers
{
    public class SearchController : Controller
    {
       
        private static HerbalList _herbalList;

        public SearchController()
        {
            if (_herbalList == null)
            {
                _herbalList = new HerbalList();
            }
            
        }
        public ActionResult Index()
        {
            return View();
            
        }


        [ChildActionOnly]
        public ActionResult latinLetters()
        {

            StringBuilder sb = new StringBuilder();
            int i = 0;
            for (char x = 'A'; x <= 'Z'; x++, i++)
            {
                sb.Append(x);
            }

            return PartialView("_Letters", sb.ToString());
        }
        [ChildActionOnly]
        public ActionResult rusLetters()
        {
            StringBuilder sb = new StringBuilder();
            int i = 0;

            for (char x = 'А'; x <= 'Я'; x++, i++)
            {
                if (x != 'Й' && x != 'Ь' && x != 'Ъ' && x != 'Ё' && x != 'Ы')
                {
                    sb.Append(x);
                }

            }

            return PartialView("_Letters", sb.ToString());
        }


        public ActionResult textList(string letter)
        {
            
            if (letter == null || letter.Length > 1)
            {

                return View("_nothingToShow");
            }

            char symbol = letter.ToUpper()[0];

            if (symbol >= 65 && symbol <= 90)
            {
                return View("_TextListLatin", _herbalList.getLatinListByFirstSymbols(letter));

            }

            if ((symbol >= 1040 && symbol <= 1065) || (symbol > 1068 && symbol <= 1071))
            {
                return View("_TextListRus", _herbalList.getDictionaryByRussianSymbols(letter));
            }

            

            return View("_nothingToShow");
        }




        public ActionResult searchAll(string s)
        {
            try
            {
                if (s.Length < 3)
                {
                    ViewBag.message = "Введите более 3-х символов для корректного поиска.";
                    return View("_nothingToShow");
                }
                List<herbDllProj.herbals> temp = new List<herbDllProj.herbals>();
                temp = _herbalList.getLatinListByAnySymbols(s);
                if (temp == null || temp.Count < 1)
                {
                    temp = _herbalList.getListByAnyRussianSymbols(s);
                }
                if (temp == null || temp.Count < 1)
                {
                    return View("_nothingToShow");
                }
                temp.ForEach(h => h.russianNames.Sort());
                ViewBag.searchedText = s;
                ViewBag.Title = "Поиск: " + s;

                return View("_CoolList", temp);
            }
            catch
            {
                return View("_nothingToShow");
            }
        }

        public ActionResult searchReseips(string r)
        {
            try
            {
                if (r.Length < 4)
                {
                    ViewBag.message = "Введите более 3-х символов для корректного поиска.";
                    return View("_nothingToShow");
                }

                List<herbDllProj.herbals> temp = new List<herbDllProj.herbals>();

                temp = _herbalList.getListByReceip(r);
                if (temp == null || temp.Count < 1)
                {
                    return View("_nothingToShow");
                }
                ViewBag.searchedText = r;
                ViewBag.Title = "Поиск: " + r;
                return View("_CoolList", temp);
            }
            catch
            {
                return View("_nothingToShow");
            }
        }
    }
}

HerbalProject/Views/Herb/Index.Mobile.cshtml
@using herbDllProj
@model herbDllProj.herbals

@{
    ViewBag.Title = @Model.name_latin;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section SearchEngine
{
    <meta name="keywords" content="@Model.name_latin, @ViewBag.Description" />
    <meta name="Description" content="Известные названия: @ViewBag.Description" />
}
@section Body{

    <div class="herbalMainDiv">

        @if (!Model.name_latin.IsEmpty())
        {
            <h1 class="latinHeader">@Model.name_latin</h1>

        }
        <div id="rusNamesDiv">
            @if (Model.russianNames != null)
            {
                <div class="RusPar">
                    @Html.Partial("_RusNames", @Model.russianNames)
                </div>
            }
        </div>

        <div style="background-image: Url('@Url.Content("~/img/images_max400/" + @Model.name_latin + "/1.jpg")')" class="herbImage" id="macroImg" onclick="showBigImage(this.id)">

        </div>

        <div style="background-image: Url('@Url.Content("~/img/images_max400/" + @Model.name_latin + "/2.jpg")')" class="herbImage" id="farImg" onclick="showBigImage(this.id)">

        </div>


        
        @if (!Model.description.IsEmpty())
        {
            <div class="par">
                <span>Описание</span>
                @Html.Partial("_Paragraph", @Model.description)
            </div>
        }

        @if (!Model.places.IsEmpty())
        {
            <div class="par">
                <span>Ареал произрастания</span>
                @Html.Partial("_Paragraph", @Model.places)
            </div>
        }

        @if (!Model.preparing.IsEmpty())
        {
            <div class="par">
                <span>Заготовка</span>
                @Html.Partial("_Paragraph", @Model.preparing)
            </div>
        }

        @if (!Model.herbal_using.IsEmpty())
        {
            <div class="par">
                <span>Применение</span>
                @Html.Partial("_Paragraph", @Model.herbal_using)
            </div>
        }

        @if (!Model.receipsTxt.IsEmpty())
        {
            <div class="receipspar">
                <span>Рекомендации к применению</span>
                @Html.Partial("_Receips", @Model.receipsTxt)
            </div>
        }

        @if (!Model.additional_info.IsEmpty())
        {
            <div class="par attention">
                @Html.Partial("_Paragraph", @Model.additional_info)
            </div>
        }

        @if (((List<herbals>)@ViewBag.relatedHerbs).Any())
        {
            <div class="par">
                <span>Похожие растения</span>
                @Html.Partial("_relatedHerbs", (List<herbDllProj.herbals>)@ViewBag.relatedHerbs)
            </div>
        }

    </div>
    <div id="bigImageWrapper" onclick="hideBigImage();" class="hide">

        <img src="@Url.Content("~/img/images_max1000/" + @Model.name_latin + "/1.jpg")" id="origImage" alt="Big herbal image" onclick="hideBigImage();" />

    </div>
}

HerbalProject/Views/Herb/Index.cshtml
@using herbDllProj
@model herbDllProj.herbals

@{
    ViewBag.Title = @Model.name_latin;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section SearchEngine
{
    <meta name="keywords" content="@Model.name_latin, @ViewBag.Description" />
    <meta name="Description" content="Известные названия: @ViewBag.Description" />
}
@section Body{

    <div class="herbalMainDiv">

        @if (!Model.name_latin.IsEmpty())
        {
            <h1 class="latinHeader">@Model.name_latin</h1>

        }

        <div style="background-image: Url('@Url.Content("~/img/images_max400/" + @Model.name_latin + "/1.jpg")')" class="herbImage" id="macroImg" onclick="showBigImage(this.id)">

        </div>

        <div style="background-image: Url('@Url.Content("~/img/images_max400/" + @Model.name_latin + "/2.jpg")')" class="herbImage" id="farImg" onclick="showBigImage(this.id)">

        </div>


        <div id="rusNamesDiv">
            @if (Model.russianNames != null)
            {
                <div class="RusPar">
                    @Html.Partial("_RusNames", @Model.russianNames)
                </div>
            }
        </div>
        @if (!Model.description.IsEmpty())
        {
            <div class="par">
                <span>Описание:</span>
                @Html.Partial("_Paragraph", @Model.description)
            </div>
        }

        @if (!Model.places.IsEmpty())
        {
            <div class="par">
                <span>Ареал произрастания:</span>
                @Html.Partial("_Paragraph", @Model.places)
            </div>
        }

        @if (!Model.preparing.IsEmpty())
        {
            <div class="par">
                <span>Заготовка:</span>
                @Html.Partial("_Paragraph", @Model.preparing)
            </div>
        }

        @if (!Model.herbal_using.IsEmpty())
        {
            <div class="par">
                <span>Применение:</span>
                @Html.Partial("_Paragraph", @Model.herbal_using)
            </div>
        }

        @if (!Model.receipsTxt.IsEmpty())
        {
            <div class="receipspar">
                <span>Рекомендации к применению:</span>
                @Html.Partial("_Receips", @Model.receipsTxt)
            </div>
        }

        @if (!Model.additional_info.IsEmpty())
        {
            <div class="par attention">
                @Html.Partial("_Paragraph", @Model.additional_info)
            </div>
        }

        @if (((List<herbals>)@ViewBag.relatedHerbs).Any())
        {
            <div class="par">
                <span>Похожие растения:</span>
                @Html.Partial("_relatedHerbs", (List<herbDllProj.herbals>)@ViewBag.relatedHerbs)
            </div>
        }

    </div>
    <div id="bigImageWrapper" onclick="hideBigImage();" class="hide">

        <img src="@Url.Content("~/img/images_max1000/" + @Model.name_latin + "/1.jpg")" id="origImage" alt="Big herbal image" onclick="hideBigImage();" />

    </div>
}

HerbalProject/Views/Herb/_Paragraph.cshtml
@model string


    @foreach (string str in Model.Split(new string[] { "\n\n" }, StringSplitOptions.RemoveEmptyEntries).ToList())
    {
        <p>@str</p>
    }

HerbalProject/Views/Herb/_Receips.cshtml
@model string


@foreach (string receip in Model.Split(new string[] { "\n\n" }, StringSplitOptions.RemoveEmptyEntries).ToList())
{

    List<string> s = receip.Split(new string[] { ":\n", ": \n" }, StringSplitOptions.RemoveEmptyEntries).ToList();
    <p>

        @if (s.Count > 1 && s[1] != null && !s[1].IsEmpty())
        {
            <span class="receipTitle">@s[0]:</span> <br />
            <span class="receipText">&nbsp;&nbsp;&nbsp;&nbsp;@s[1]</span>
            
        }else if(@s.Count == 1){
            <span class="receipTitle">@s[0]</span> <br /> 
        }

    </p>


}

HerbalProject/Views/Herb/_RusNames.Mobile.cshtml
@model List<string>
@{
    string text = string.Empty;
 foreach (string name in @Model.OrderBy(n => n))
 {
     text += name + ", ";
 }
    text = text.TrimEnd(new char[] {',', ' '});
}
    
@text

HerbalProject/Views/Herb/_RusNames.cshtml
@model List<string>

<ul>
    @foreach (string name in @Model.OrderBy(n=>n))
    {
        <li>@name</li>
    }
</ul>

HerbalProject/Views/Herb/_relatedHerbs.cshtml
@model List<herbDllProj.herbals>

@foreach (var item in @Model)
{
    @Html.Partial("_CoolListItem", item);

}

HerbalProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Онлайн справочник лекарственных растений";
}


@section Body{
    
    <div id="herbalMainDiv">
        
        <div class="par">
            <span>Сила растений</span>
            <p>С древнейших времен люди использовали силу лекарственных растений для лечения различных заболеваний. 
            Шумерская медицина, вавилонская, китайская, древнегречиская, тибетская и другие положили начало использованию растений не только как пищи, но и как средство борьбы с различныи заболеваниями.
            И в наше время совершенно необязательно глотать горсть таблеток, что бы вылечить свой недуг.</p>

            <p>С появлением особого сословия врачей и аптекарей знания о лекарственных растениях были формализованы. Сведения о лекарственных растениях и требования к лекарственному сырью стали излагать в фармакопеях.
В настоящее время в программе обучения в медицинских и фармацевтических институтах входит курс фармакогнозии.
В народной медицине находят применение и неофицинальные лекарственные растения, круг которых не имеет чётких границ.</p>

        </div>

        <div class="par">
            <span>Применение лекарственных растений</span>
            <p>
                В лекарственных травах содержится минимум одно вещество, обладающее лечебными свойствами. 
                Это вещество или вещества зачастую неравномерно распределены по тканям и частям растения. 
                Поэтому при сборе лекарственных трав надо знать, где сосредоточены полезные элементы и в какой период развития растения их концентрация максимальна.
                Из официнальных растений получают различные морфологические группы лекарственного растительного сырья: трава, цветки, листья, корневища, корни, плоды, семена, кора, почки и др.
            </p>
            <p>
                Основные способы применения сырья лекарственных растений: производство лекарственных средств для внутреннего и наружного применения.
                Внутрь применяют водные извлечения: настой, отвар, водно-спиртовые, масляные извлечения (настойка, экстракты) из лекарственного растительного сырья или сборов. Из сочных свежих частей официнальных растений получают сок. Реже находит применение в медицине порошок из высушенного лекарственного растительного сырья.
                Для наружного применения используются: травяная ванна, обертывание, примочка, компресс.
            </p>            
        </div>

</div>
}

HerbalProject/Views/Home/PageNotFound.cshtml
@{
    ViewBag.Title = "PageNotFound";
}

@section Body{
    <div id="herbalMainDiv">
        <div class="par">

            <span>Page not found</span>
            <p style="text-align: center;">Страница не найдена. Проверьте введенный адрес.</p>
        </div>

    </div>
}

HerbalProject/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Результаты поиска";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@using System.Web.Mvc.Html;

@section Body{

    <div id="message">@ViewBag.message</div>

}

HerbalProject/Views/Search/_CoolList.cshtml
@model List<herbDllProj.herbals>


@section Body{
    <div id="coolListWrapper">
        <span>Результаты поиска по запросу: "@ViewBag.searchedText" <span style="font-size: smaller;">(@Model.Count растений)</span> </span>

        @foreach (var item in @Model)
    {
            @Html.Partial("_CoolListItem", item);

    }
    </div>

}

HerbalProject/Views/Search/_CoolListItem.cshtml
@model herbDllProj.herbals

<div class="coolListItem">
    <div style="background-image:Url('@Url.Content("~/img/images_max200/"+@Model.name_latin+"/1.jpg")')" class="CoolItemPic">

    </div>

    
    <span class="coolListItemTitle">@Html.ActionLink(@Model.name_latin, "Index", "Herb", "http", null, null, new { name = @Model.name_latin.Replace(' ', '_') }, null) <br /></span>

    <ul class ="CollListitemCol1">
        @for (int i = 0; i < @Model.russianNames.Count; i++)
        {
            if (i < 5)
            {
                <li>@Model.russianNames[i]</li>
            }
        }

    </ul> 
   
    <ul class="CollListitemCol1">
        @for (int i = 0; i < @Model.russianNames.Count; i++)
        {
            if (i >= 5 && i < 11)
            {
                <li>@Model.russianNames[i]</li>
            }
        }

    </ul>
    <ul class="CollListitemCol1">
        @for (int i = 0; i < @Model.russianNames.Count; i++)
        {
            if (i >= 11 && i <= 17)
            {
                <li>@Model.russianNames[i]</li>
            }
        }

    </ul>












</div>

HerbalProject/Views/Search/_Letters.cshtml
@model String
@using System.Web.Mvc.Html


@for (int i = 0; i < Model.Length; i++){

    
    @Html.ActionLink(@Model[i].ToString(),"textList","Search",new { letter = @Model[i] },null)
}

HerbalProject/Views/Search/_TextListLatin.Mobile.cshtml
@model List<string>

@{
    ViewBag.Title = "Растения на букву \"" + @Model[0][0] + "\"";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int columns = 3;

    int itemsInColumns = (@Model.Count % columns) == 0 ? (@Model.Count / columns) : (@Model.Count / columns + (@Model.Count % columns));

}
@section Body{
    <div id="textSearchResultList">
        <h1 class="latinHeader">Растения на букву "@Model[0][0]"</h1>

        <div id="searchColumns">

            <div class="searchListColumn">
                @foreach (var item in @Model)
                {
                    @Html.ActionLink(@item, "Index", "Herb", "http", null, null, new { name = item.Replace(' ', '_').Replace('.', '!') }, null)

                }
            </div>

        </div>
    </div>
}

HerbalProject/Views/Search/_TextListLatin.cshtml
@model List<string>

@{
    ViewBag.Title = "Растения на букву \"" + @Model[0][0]+"\"";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int columns = 4;
    int itemsInColumns = (@Model.Count % columns) == 0 ? (@Model.Count / columns) : (@Model.Count / columns + (@Model.Count % columns));

}
@section Body{
    <div id="textSearchResultList">
        <h1 class="latinHeader">Растения на букву "@Model[0][0]"</h1>
        @for (int i = 0; i < columns; i++)
        {
            <div class="searchListColumn">
                @for (int j = itemsInColumns*i; j < itemsInColumns*i + itemsInColumns; j++)
                {
                    if (@Model.Count > j)
                    {
                        @Html.ActionLink(@Model[j], "Index", "Herb", "http", null, null, new {name = @Model[j].Replace(' ', '_').Replace('.', '!')}, null)
                    }

                }
            </div>

        }


    </div>
}

HerbalProject/Views/Search/_TextListRus.Mobile.cshtml
@model List<herbDllProj.HerbalList.RusLatinDictionary>

@{
    ViewBag.Title = "Растения на букву \"" + @Model[0].key[0] + "\"";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
}
@section Body{

    <div id="textSearchResultList">
        <h1 class="latinHeader">Растения на букву "@Model[0].key[0]"</h1>

        <div id="searchColumns">

            <div class="searchListColumn">
                @foreach (var item in @Model)
                {
                    <a href="@Url.Action("Index", "Herb", new {name = @item.value.Replace(' ', '_').Replace('.', '!')})">@item.key<span style="font-size: smaller; margin-left: 1vw;">(@item.value)</span></a>
                   
                }
            </div>

        </div>
    </div>

}

HerbalProject/Views/Search/_TextListRus.cshtml
@model List<herbDllProj.HerbalList.RusLatinDictionary>

@{
    ViewBag.Title = "Растения на букву \""+ @Model[0].key[0] + "\"";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int columns = 4;

    int itemsInColumns = (@Model.Count % columns) == 0 ? (@Model.Count / columns) : (@Model.Count / columns + (@Model.Count % columns));

}
@section Body{
    
    <div id="textSearchResultList">
        <h1 class="latinHeader">Растения на букву "@Model[0].key[0]"</h1>
        @for (int i = 0; i < columns; i++)
        {
            <div class="searchListColumn">
                @for (int j = itemsInColumns * i; j < itemsInColumns * i + itemsInColumns; j++)
                {
                    if (@Model.Count > j)
                    {
                        <a href="@Url.Action("Index", "Herb", new { name = @Model[j].value.Replace(' ', '_').Replace('.', '!') })"> @Model[j].key<br/>(@Model[j].value)</a>
                        //@Html.ActionLink(, "Index", "Herb", "http", null, null, new { name = @Model[j].value.Replace(' ', '_') }, null)
                    }

                }
            </div>

        }


    </div>
}

HerbalProject/Views/Search/_textList.cshtml
@model List<string>

@{
    ViewBag.Title = "_textList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Body{
    @foreach (var item in @Model)
    {
        @Html.ActionLink(@item, "Index", "Herb", "http", null, null, new { name = @item.Replace(' ', '_') }, null) <br />
    }
}

HerbalProject/Views/Shared/_CoolListItem.cshtml
@model herbDllProj.herbals

<div class="coolListItem">

    <a href="/herb/@Model.name_latin.Replace(' ', '_').Replace('.', '!')">
        <div>
            <div class="coolItemWrapper">
                <div style="background-image: Url('@Url.Content("~/img/images_max200/" + @Model.name_latin + "/1.jpg")')" class="CoolItemPic">

                </div>

                <span class="coolListItemTitle" >@Model.name_latin</span>

                <ul class="CollListitemCol1">
                    @for (int i = 0; i < @Model.russianNames.Count; i++)
                    {
                        if (i <= 4)
                        {
                            <li>@Model.russianNames[i]</li>
                        }
                    }

                </ul>

                @if (@Model.russianNames.Count > 4)
                {
                    <ul class="CollListitemCol1">
                        @for (int i = 0; i < @Model.russianNames.Count; i++)
                        {
                            if (i > 4 && i <= 9)
                            {
                                <li>@Model.russianNames[i]</li>
                            }
                        }

                    </ul>
                }
                @if (@Model.russianNames.Count > 9)
                {
                    <ul class="CollListitemCol1">
                        @for (int i = 0; i < @Model.russianNames.Count; i++)
                        {
                            if (i > 9 && i <= 14)
                            {
                                <li>@Model.russianNames[i]</li>
                            }
                        }

                    </ul>
                }

                @if (@Model.russianNames.Count > 14)
                {
                    <ul class="CollListitemCol1">
                        @for (int i = 0; i < @Model.russianNames.Count; i++)
                        {
                            if (i > 14 && i <= 17)
                            {
                                <li>@Model.russianNames[i]</li>
                            }
                        }

                    </ul>
                }

            </div>
        </div>
    </a>








</div>

HerbalProject/Views/Shared/_Footer.cshtml
Created By SD - @System.DateTime.Today.Year

HerbalProject/Views/Shared/_Layout.Mobile.cshtml
@using System.Web.Optimization;

<!DOCTYPE html>
<html>
<head>

    <title>@ViewBag.Title</title>
    
    <link href="~/Content/Site_mobile.css" rel="stylesheet" />
    <script src="~/Scripts/script_mobile.js"></script>
    <link rel="shortcut icon" type="image/png" href="~/Content/favicon.png"/>
    <link rel="icon" type="image/png" href="~/Content/favicon.png" />
    @RenderSection("SearchEngine", false)
    <script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-68237835-1', 'auto');
    ga('send', 'pageview');

    </script>
</head>
<body>
    <div id="antiScrollBar">
        <div id="globalDiv">
            
            <div id="headerDiv">
                <img src="~/img/title.png" />
            </div>

            <div id="searchDiv">
                @Html.Partial("_SearchLetters")
                @Html.Partial("_searchBlock")
            </div>

            <div id="mainPageDiv">
                <div id="contentDiv">
                    @RenderSection("Body")
                </div>
            </div>

            <div id="googleAds">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <ins class="adsbygoogle"
                     style="display: block"
                     data-ad-client="ca-pub-4409879172881990"
                     data-ad-slot="5724711862"
                     data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>


        </div>
    </div>
</body>
</html>

HerbalProject/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    <link href="~/Content/Site.min.css" rel="stylesheet" />
    <script src="~/Scripts/script.js"></script>
    <link rel="shortcut icon" type="image/png" href="~/Content/favicon.png"/>
    <link rel="icon" type="image/png" href="~/Content/favicon.png" />
    @RenderSection("SearchEngine", false)
    <script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-68237835-1', 'auto');
    ga('send', 'pageview');

    </script>
</head>
<body>
    <div id="globalDiv">

        <div id="headerDiv">
            <span>herbal-info.ru  </span><span>Онлайн справочник лекарственных растений</span>
        </div>

        <div id="searchDiv">
            @Html.Partial("_SearchLetters")
            @Html.Partial("_searchBlock")
        </div>

        <div id="googleAds">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-4409879172881990"
                 data-ad-slot="5724711862"
                 data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>

        <div id="mainPageDiv">
            <div id="contentDiv">
                @RenderSection("Body")
            </div>


        </div>

        
    </div>
    
</body>
</html>

HerbalProject/Views/Shared/_SearchLetters.cshtml
<div id="allLetters">
    <div class="tooltip">
        <span>Поиск по первой букве в международной номенклатуре</span>
        <div class="Linkletters" id="latinLetters">
            @Html.Action("latinLetters", "Search", null)
        </div>
    </div>

    <div class="tooltip">
        <div class="Linkletters" id="rusLetters">
            <span style="margin-left:45px;">Поиск по первой букве в народных названиях</span>
            @Html.Action("rusLetters", "Search", null)
        </div>
    </div>
</div>

HerbalProject/Views/Shared/_nothingToShow.cshtml
@{
    ViewBag.Title = "Поиск не дал результатов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Body{
    <div id="textSearchResultList">
    @if (@ViewBag.message == null)
    {
        <h3 style="text-align:center;">Поиск не дал результатов.<br /> Проверьте правильность введенных данных.</h3>
    }
    <h3>@ViewBag.message</h3>
</div>

}